heroku:
  stage: deploy
  only:
    - main
  before_script:
    - apk update && apk add git
    - git --version
  script:
    - git remote rm heroku
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/reservenow.git
    - git push heroku HEAD:main
  environment:
    name: production
    url: https://reservenow.herokuapp.com/
