heroku:
  stage: deploy
  only:
    - main
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/reservenow.git
    - git push heroku main
  environment:
    name: production
    url: https://reservenow.herokuapp.com/
