heroku:
  stage: deploy
  only:
    - main
  before_script:
    - apk update && apk add git
    - git --version
  script:
    - git push -f heroku master
  environment:
    name: production
    url: https://reservenow.herokuapp.com/
