heroku:
  stage: deploy
  only:
    - main
  before_script:
    - apk update && apk add git
  script:
    #    - git remote rm heroku
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/premosson.git
    #    - git remote set-url heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/premosson.git
    - git push heroku HEAD:main
  environment:
    name: production
    url: https://premosson.herokuapp.com/
